[package]
name = "domato"
version = "0.1.0"
edition = "2021"

[dependencies]
bisection = "0.1.0"
html-escape = "0.2.13"
lazy_static = "1.4.0"
once_cell = "1.19.0"
rand = "0.8.5"
regex = "1.10.4"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
thiserror = "1.0.60"
